version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nest_db
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: nest_user
      DATABASE_PASSWORD: nest_password
      DATABASE_NAME: nest_db
      JWT_SECRET: super_secure_jwt_secret
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"

volumes:
  mysql-data:
